export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';
export const ADD_GENRE_REQUEST = 'ADD_GENRE_REQUEST';
export const ADD_GENRE_SUCCESS = 'ADD_GENRE_SUCCESS';
export const ADD_GENRE_FAILURE = 'ADD_GENRE_FAILURE';
